---
title: "Data Challenge"
author: "Sutong Zhang"
date: "2023-05-02"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(ggplot2)
library(tidyverse)
library(dplyr)
library(caret)
library(randomForest)
library(forecast)
library(shiny)
library(corrplot)
```

Data processing
```{r}
#Input data
CE <- read.csv("~/Downloads/Electricity_Revenue_in_Colorado.csv")
```

CE
```{r}
#Cleaning data
CENew <- CE %>%
  select(year,residentialRevenue,residentialSales,commercialRevenue,commercialSales,industrialRevenue,industrialSales,transportationRevenue,transportationSales,otherRevenue,otherSales,totalRevenue,totalSales) %>%
  group_by(year) %>%
  summarize(residentialRevenue = sum(residentialRevenue),residentialSales = sum(residentialSales), commercialRevenue = sum(commercialRevenue), commercialSales = sum(commercialSales), industrialRevenue = sum(industrialRevenue), industrialSales = sum(industrialSales), transportationRevenue = sum(transportationRevenue), transportationSales = sum(transportationSales), otherRevenue = sum(otherRevenue), otherSales = sum(otherSales), totalRevenue = sum(totalRevenue), totalSales = sum(totalSales))

#Plot Sales
long_CESale <- CENew %>%
  select(year,residentialSales,commercialSales,industrialSales,transportationSales,otherSales,totalSales) %>%
  pivot_longer(cols = -year, names_to = "Sales", values_to = "Value")
 CESale <- ggplot(long_CESale, aes(x = year, y = Value, color = Sales, group = Sales)) +
  geom_line() +
  geom_point() +
  ylab("Megawatt") +
  xlab("Year") +
  ggtitle("Number of megawatt hours sold") +
  theme_minimal()
CESale

#Plot Revenues
long_CERev <- CENew %>%
  select(year,residentialRevenue,commercialRevenue,industrialRevenue,transportationRevenue,otherRevenue,totalRevenue) %>%
  pivot_longer(cols = -year, names_to = "Revenue", values_to = "Value")
 CERev <- ggplot(long_CERev, aes(x = year, y = Value, color = Revenue, group = Revenue)) +
  geom_line() +
  geom_point() +
  ylab("Thousands of dollar") +
  xlab("Year") +
  ggtitle("Revenue from electricity consumption") +
  theme_minimal()
CERev

#Total Proportional
long_CESale2 <- CENew %>%
  select(year,residentialSales,commercialSales,industrialSales,transportationSales,otherSales) %>%
  pivot_longer(cols = -year, names_to = "Sales", values_to = "Value")
CESale.P <- ggplot(long_CESale2, aes(fill = Sales, y = Value, x = year)) + 
  geom_bar(position="fill", stat="identity") +
  ylab("Percentage")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  ggtitle("Percentage number of megawatt hours sold")
CESale.P
long_CERev2 <- CENew %>%
    select(year,residentialRevenue,commercialRevenue,industrialRevenue,transportationRevenue,otherRevenue) %>%
  pivot_longer(cols = -year, names_to = "Revenue", values_to = "Value")
CERev.P <- ggplot(long_CERev2, aes(fill = Revenue, y = Value, x = year)) + 
  geom_bar(position="fill", stat="identity") +
  ylab("Percentage")+
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) + 
  ggtitle("Revenue from electricity consumption")
CERev.P

#Price
CEPrice <- CE %>%
    select(year,month,residentialPrice,commercialPrice,industrialPrice,transportationPrice,otherPrice,totalPrice)
CEPrice$date <- as.Date(paste(CEPrice$year, CEPrice$month, "01", sep = "-"), format = "%Y-%m-%d")
CEPriceN <- CEPrice %>%
    select(date,residentialPrice,commercialPrice,industrialPrice,transportationPrice,otherPrice,totalPrice)
long_CEPrice <- CEPriceN %>%
  select(date,residentialPrice,commercialPrice,industrialPrice,transportationPrice,otherPrice,totalPrice) %>%
  pivot_longer(cols = -date, names_to = "Price", values_to = "Value")
 CEPri <- ggplot(long_CEPrice, aes(x = date, y = Value, color = Price, group = Price)) +
  geom_line() +
  geom_point() +
  ylab("Price in cents") +
  xlab("Year") +
  ggtitle("Price in cents per kilowatt hour") +
  theme_minimal()
CEPri
```
Model
```{r}
Mod <- CE %>%
  select(year,month,totalRevenue,totalCustomers,totalPrice) %>%
  mutate(across(everything(), ~ifelse(is.na(.), mean(., na.rm = TRUE), .)))

cor_matrix <- cor(Mod %>% select(month, totalRevenue, totalCustomers,totalPrice))
print(cor_matrix)
corplot <- corrplot(cor_matrix, method = "circle")
set.seed(42)
train_index <- sample(nrow(Mod), 0.8 * nrow(Mod))
train_data <- Mod[train_index, ]
test_data <- Mod[-train_index, ]

# Fit linear regression model
model1 <- lm(totalRevenue ~ month + totalCustomers + totalPrice, data = train_data)
summary(model)
predictions <- predict(model, test_data)
test_data$predictions <- predictions
print(test_data)
mse1 <- mean((test_data$totalRevenue - test_data$predictions)^2)
print(mse1)
 m1 <- ggplot(test_data, aes(x = totalRevenue, y = predictions)) +
  geom_point(color = "blue") +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  labs(
    x = "Actual total revenue",
    y = "Predicted total revenue",
    title = "Actual vs Predicted total revenue"
  ) +
   theme_minimal()
m1
# Fit Random Forest
train_control <- trainControl(
  method = "cv", # Cross-validation
  number = 5,    # Number of folds
  search = "grid" # Grid search for hyperparameter tuning
)
param_grid <- expand.grid(
  mtry = seq(1, ncol(train_data) - 1, 1) 
)
# Train the model with hyperparameter tuning
set.seed(42)
model2 <- train(
  totalRevenue ~ month + totalCustomers + totalPrice, 
  data = train_data,
  method = "rf", # Random Forest
  metric = "RMSE", # Root Mean Squared Error as the optimization metric
  trControl = train_control,
  tuneGrid = param_grid
)
print(model2)
predictions2 <- predict(model2, test_data)
test_data$predictions2 <- predictions2
print(test_data)
mse2 <- mean((test_data$totalRevenue - test_data$predictions2)^2)
print(mse2)

m2 <- ggplot(test_data, aes(x = totalRevenue, y = predictions2)) +
  geom_point(color = "blue") +
  geom_abline(intercept = 0, slope = 1, color = "red", linetype = "dashed") +
  labs(
    x = "Actual total revenue",
    y = "Predicted total revenue",
    title = "Actual vs Predicted total revenue"
  ) +
  theme_minimal()
m2
#Time Series Forecasting
Mod$date <- as.Date(paste(Mod$year, Mod$month, "01", sep = "-"), format = "%Y-%m-%d")
print(Mod)

ts_data <- ts(Mod)
model3 <- auto.arima(ts_data[,6])
print(model3)
# Forecast the next 15 time steps
forecast_steps <- 15
forecast_result <- forecast(model3, h = forecast_steps)
print(forecast_result)
m3 <- plot(forecast_result)
m3
```

shiny
```{r}
# Define the Shiny app UI
ui <- fluidPage(
  titlePanel("Electricity Balancing in Corolado Analysis"),
  fluidRow(
    column(4, plotOutput("scatterPlot1")),
    column(4, plotOutput("scatterPlot2")),
    column(4, plotOutput("scatterPlot3")),
    column(4, plotOutput("scatterPlot4")),
    column(4, plotOutput("scatterPlot5")),
    column(4, plotOutput("scatterPlot6")),
    column(4, plotOutput("scatterPlot7")),
    column(4, plotOutput("scatterPlot8")),
    column(4, plotOutput("scatterPlot9")),
  )
)


# Define the Shiny app server
server <- function(input, output) {
  output$scatterPlot1 <- renderPlot({
    CESale
  })
  output$scatterPlot2 <- renderPlot({
    CERev
  })
   output$scatterPlot3 <- renderPlot({
    CESale.P
  })
    output$scatterPlot4 <- renderPlot({
    CERev.P
  })
     output$scatterPlot5 <- renderPlot({
    CEPri
  })
     output$scatterPlot6 <- renderPlot({
    corplot
  })
      output$scatterPlot7 <- renderPlot({
    m1
  })
       output$scatterPlot8 <- renderPlot({
    m2
  })
        output$scatterPlot9 <- renderPlot({
    m3
  })
}

# Run the Shiny app
shinyApp(ui = ui, server = server)

```
